// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnijlpjpdtzwkrsrvqvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuaWpscGpwZHR6d2tyc3J2cXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTk4MzUsImV4cCI6MjA2ODA3NTgzNX0.0I37KZv0ljnRC9EOdSPh-O08TWW9usQmw-vn-w8i1Ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});